### ISSUE TITLE
Revenant summons IA dont properly follow the player

### ISSUE THREAD

**Issue by potor123** [muon-rw/Medieval-Origins-Old#104]
Revenant summons behaves very weirdly, sometimes they just stop following you or dont teleport anymore.
Perhaps a bit of attention to that, or maybe a skill to force all summons to teleport to you would be cool.

**Comment by muon-rw** [comment]
With the latest update they have a mix of undead behavior/pet behavior, and they’ll teleport if you get too far away. 

I like the idea of summoning them on command, I’ll probably add an item for it which could also be used to reset their AI state.
