### ISSUE TITLE
Some powers missing or only partially functioning

### ISSUE THREAD

**Issue by Chrono-Eventless** [muon-rw/Medieval-Origins-Old#112]
i started a world and looking at it from the selection screen i can see the ethereal (but without a keybind for some reason) and both curse related perks 

but when i actually spawn in looking at the origin menu doesn't show them and i can't seem to turn ethereal

**Comment by Chrono-Eventless** [comment]
update: they seem to be back for some reason after rejoining the world the next day

**Comment by EnderTim** [comment]
I had the same error. I tested it with diffrent races. and it seems to be on all races.

**Comment by muon-rw** [comment]
This is likely an underlying issue with how Origins handles networking, exposed by any sufficiently large or complex origin. 

If you have this issue, try installing the Connectivity mod. If issues persist you might also try Packet Fixer.
