### ISSUE TITLE
Dwarf Photoallergic burns with helmet on but not off

### ISSUE THREAD

**Issue by Stalros** [muon-rw/Medieval-Origins-Old#12]
Dwarves dont burn in the sunlight without a helmet (but they are blind)
Wearing a helmet triggers the burning, for some reason

Gold helmet taking away blindness works properly, but the dwarf in question immediately begins burning upon equipping it.

**Comment by muon-rw** [comment]
Hi, which mod version are you playing?

Do you have AutoTag in your mods list?

**Comment by muon-rw** [comment]
Fixed in the next release.
