### ISSUE TITLE
Valkyrie Origin "Heavenly Implements" passive ability doesn't apply to the Ice and Fire mods' "Tide Trident"

### ISSUE THREAD

**Issue by GracefulBlades** [muon-rw/Medieval-Origins-Old#127]
Just as the title describes the **Valkyrie**'s "Heavenly Implements" passive doesn't apply to _Ice and Fire's_ "Tide Trident" (atleast the tooltip doesn't show)

**Comment by muon-rw** [comment]
The tooltip is the same check, so it’s probably not being picked up. Thanks for the report
