### ISSUE TITLE
Aquaculture 2 fish aren't carnivore food

### ISSUE THREAD

**Issue by Javiondox** [muon-rw/Medieval-Origins-Old#130]
![imagen](https://github.com/user-attachments/assets/08c17ce6-61d6-4a80-b409-3c18e55a0863)

**Comment by muon-rw** [comment]
Technically this is a compatibility issue with Origins itself, but I have a datapack that fixes it. 

Here:
https://www.curseforge.com/minecraft/texture-packs/origins-expanded-foods
