### ISSUE TITLE
Valkyrie Origin

### ISSUE THREAD

**Issue by TheFireSkorpion** [muon-rw/Medieval-Origins-Old#133]
I don't know if you've done this before, but the Valkyrie has a -50% speed and damage effect against the living dead, which means that it has a slowness of 4 and a weakness of 4, which means that when faced with 2 or more zombies in a building, and you use a spear... it's death because you can't flee or kill them quickly, because even with a spear, you still have a -25% attack damage.

**Comment by muon-rw** [comment]
You also have powered flight from the beginning of the game

**Comment by TheFireSkorpion** [comment]
Yes, a flight that's useless indoors ... make a game and try to play 15mn with see if it is so easy to fly knowing that at the slightest error in try to flee and the fact that the slowness affects the flight makes you end up in walls or on the ground which in the rare case where you manage to flee you end up dead of fall damage

**Comment by FemBane** [comment]
Speaking of the early-game flight, would it be possible to add a keybind, or possible make the secondary origin ability of it to toggle flight? Some movement mods don't like elytra flight, like parcool, so trying to wall-jump, or just ledge-hanging can make you initiate flight.
