### ISSUE TITLE
Incompatible with Timeless and Classics Zero (TACZ)

### ISSUE THREAD

**Issue by Fl414r** [muon-rw/Medieval-Origins-Old#135]
[latest.txt](https://github.com/user-attachments/files/16715209/latest.txt)

So... ye, for some reason MOR crashes with TACZ

Also this report on TACZ github https://github.com/MCModderAnchor/TACZ/issues/192

**Comment by muon-rw** [comment]
It looks like a Mixin conflict with a library mod I use, Apugli. 

I doubt the Apugli dev has any interest in fixing this, but I’m looking to migrate away from the Apugli dependency at some point anyway (it just has a lot of overhead I’m not using). 

When that happens, TACZ should be compatible.

**Comment by muon-rw** [comment]
As of 7.0.0, Apugli is no longer used.
