### ISSUE TITLE
Crash When getting hit/hitting enemy as Revenant

### ISSUE THREAD

**Issue by axijiku** [muon-rw/Medieval-Origins-Old#137]
[crash-2024-08-23_16.27.50-server.txt](https://github.com/user-attachments/files/16734489/crash-2024-08-23_16.27.50-server.txt)
[latest.log](https://github.com/user-attachments/files/16734494/latest.log)

I'm also having a similar issue with the Valkyrie class, not sure what could be causing it. I included a crash log and latest log report.

**Comment by muon-rw** [comment]
I’m guessing this is why you closed the issue, but this is caused by an outdated version of Spell Engine.

If you’re playing Prominence RPG, you can either wait for Prom RPG Hasturian Era, or use version 6.3.0 of this mod.

**Comment by axijiku** [comment]
Yeah that would be why, thank you for the reply though. I appreciate it!
