### ISSUE TITLE
Siren's Song not working

### ISSUE THREAD

**Issue by MARINAPLAYZ** [muon-rw/Medieval-Origins-Old#138]
The hearts and the angelic music happens but mobs still attack me.

**Comment by MARINAPLAYZ** [comment]
[https://i.imgur.com/BFc1n8U.mp4](url)

**Comment by muon-rw** [comment]
It seems like the mobs_ignore power type (what Siren’s Song uses) isn’t really well suited for interrupting combat aggro like this. 

I’ll see about an alternative

**Comment by MARINAPLAYZ** [comment]
> It seems like the mobs_ignore power type (what Siren’s Song uses) isn’t really well suited for interrupting combat aggro like this.
> 
> I’ll see about an alternative

Thank you! How exactly is it supposed to work?

**Comment by muon-rw** [comment]
Currently it should prevent any mobs from *becoming* aggressive toward you, but may be pretty inconsistent when trying to interrupt mobs that already are

**Comment by muon-rw** [comment]
Fixed in 7.0.0
