### ISSUE TITLE
[Forge] Sirens crash when taking fire damage

### ISSUE THREAD

**Issue by amehunter** [muon-rw/Medieval-Origins-Old#14]

**Comment by muon-rw** [comment]
Hi, which mod version are you playing? 

Can you send a crash report or log file?

**Comment by amehunter** [comment]
of course, sorry for not providing this the first time ^^
mod vers: 5.1.9.1 (1.20.1, most recent vers)
[latest.log](https://github.com/muon-rw/Medieval-Origins-Revival/files/13058110/latest.log)

**Comment by muon-rw** [comment]
Seems to be a bug with Origins Forge. I’ll look into an alternate method for applying this debuff
