### ISSUE TITLE
Siren song heart effect won't go away

### ISSUE THREAD

**Issue by AlienatedCashew** [muon-rw/Medieval-Origins-Old#140]
My friend used siren song near me on our server yesterday and the heart effect has not gone away after I've left, slept, and died.

**Comment by muon-rw** [comment]
This should not happen on 6.4.5 - If you're playing a modpack, they may have an older version. 

To clear the effect once you've updated, you may need to run
`/power revoke @s medievalorigins:siren/captivated apoli:command`
