### ISSUE TITLE
Revenant Summons don't drop items you gave them

### ISSUE THREAD

**Issue by PearlOfficial** [muon-rw/Medieval-Origins-Old#141]
Version 1.20.1

How to replicate:
- Open game
- Pick Revenant class
- Use primary key to summon a summon
- Give summon any sword/bow
- Kill Summon
- Summon will not drop any items or xp

**Comment by muon-rw** [comment]
This definitely *shouldn’t* be the case, it was tested as such. Will take another look at it.
