### ISSUE TITLE
Revenant unable to eat bones with full hunger bar, despite them not providing any nutrition

### ISSUE THREAD

**Issue by PearlOfficial** [muon-rw/Medieval-Origins-Old#144]
Version 1.20.1

### How to replicate:
- Open game
- Pick Revenant class
- Switch gamemode to survival
- Check if hunger is full
- Try to eat a bone (will fail)

### Why should this be fixed:
It is quite unintuitive and annoying having to remain below maximum hunger to eat something that will provide no nutrition.
If even in vanilla Minecraft Honey Bottles can be consumed with a full hunger bar (bc of the detoxicating effect) it would be quite reasonable to enable a Revenant to consume bones/flesh at any time to recharge the summoning bars.

In my personal opinion this fits well within the current game balance, and it removes the necessity to jump around like a lunatic just to loose hunger, which is a ridiculous prerequisite to beginn with, considering the bars take quite a bit of bone/flesh to fill up.

It would make the game more consistent, and playing Revenant more enjoyable.

**Comment by muon-rw** [comment]
Fixed in upcoming 1.21.1 release - unlikely to backport unfortunately
