### ISSUE TITLE
mermod still dosent work in forge even tho 6.4.5 is installed

### ISSUE THREAD

**Issue by Ikerrd2115** [muon-rw/Medieval-Origins-Old#145]
i`ve beeen trying to set up a pack with mermod and medieval origins revival but it seams to not work even tho i have installed the latest version in witch this sould work the errror mesage is as follows:

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class dev.muon.medievalorigins.power.factory.MermodTailPowerFactory cannot be cast to class io.github.thatpreston.mermod.forge.compat.origins.TailPowerFactory (dev.muon.medievalorigins.power.factory.MermodTailPowerFactory is in module medievalorigins@6.4.5+1.20.1-forge of loader 'TRANSFORMER' @638977e0; io.github.thatpreston.mermod.forge.compat.origins.TailPowerFactory is in module mermod@3.0.1 of loader 'TRANSFORMER' @638977e0)

**Comment by muon-rw** [comment]
Yes, you’ll have to use an older version of Medieval Origins for now, Mermod added their own integration which is incompatible.

**Comment by Ikerrd2115** [comment]
thxxx
