### ISSUE TITLE
Configuration for origins.

### ISSUE THREAD

**Issue by AnthonyJacksonDM** [muon-rw/Medieval-Origins-Old#15]
Hello! Would you be able to set up some sort of config file as to better modify the races? I'm currently running a server and was hoping to give dwarves more options in helmet variety since it seems that only gold is usable for them without issues.

**Comment by muon-rw** [comment]
At the moment, you could add other helmets to the medievalorigins:golden_armor item tag with a datapack, or disable photoallergic and darkness_dweller in your origins_server or origins-common config. 

There’s a major rework in progress which will change this dwarf downside anyway, so I probably won’t add any other configurability yet.

**Comment by muon-rw** [comment]
Enchantment alternative implemented in 6.0.0
