### ISSUE TITLE
I don't know where "medievalorigins:is_cursed" is located.

### ISSUE THREAD

**Issue by doa-park** [muon-rw/Medieval-Origins-Old#150]
I am a Korean user and I am not good at English, so my sentences may be immature.

I'm making a modpack to enjoy with friends, and I found that curse enchantments from other mods don't apply to cursed_sigil.

I would like to have curse enchantments from other mods also apply to cursed_sigil. Can you help me?

**Comment by muon-rw** [comment]
This is hardcoded, but it should apply to any enchantment that properly Overrides `isCurse`

https://github.com/muon-rw/Medieval-Origins-Revival/blob/aff84fd1ea8b16937586c00550185f40f959cbdd/fabric/src/main/java/dev/muon/medievalorigins/condition/ModItemConditions.java#L18-L20

**Comment by doa-park** [comment]
Thanks for letting me know, but I'm not good at coding so I don't know how to fix it.

Sorry, but can you also tell me how to fix it?

**Comment by muon-rw** [comment]
It's likely just an issue with however that mod adds the curse, and not much you can do on your end. 

Could you link me to a mod whose curses aren't working as expected?
