### ISSUE TITLE
Pixie Flight Controls Reversed in Bewitchment Transformations or Icarus Wing Flight

### ISSUE THREAD

**Issue by rruy-dev** [muon-rw/Medieval-Origins-Old#151]
Issue:
When in a Bewitchment/Besmirchment Transformation, such as Werewolf or Werepyre, Pixie flight controls are reversed. 
Crouching ascends, and Jumping descends.
This also occurs if Icarus wings are equipped, you begin gliding, then activate Pixie flight while the wings are still open.

I tried narrowing down to if it was an issue with a specific Pixie power using `/power remove`... but doesn't seem to be an issue with a specific power.

Occurring on the modpack Fantasy MC Fabric, has Medieval Origins Revival v6.4.5.
I did personal testing in singleplayer with v6.4.6, and the issue is present there too.

**Comment by muon-rw** [comment]
Well, that's an odd one, but given Pixie flight just grants the vanilla creative flight ability, I would guess there's not too much to be done on my end.

**Comment by rruy-dev** [comment]
We figured out the issue with players losing their flight by using commands to teleport between dimensions, is caused a bug in FTB Essentials, so can continue to troubleshoot from there.
Thanks for clarifying the way the flight works is by granting creative flight, wouldn't have known where to start w/o that hint
