### ISSUE TITLE
(balance) Cutlasses receive Moonlight Rogue damage + stealth break bonus

### ISSUE THREAD

**Issue by ghotiPhoti** [muon-rw/Medieval-Origins-Old#154]
Is there a way for me to reconfigure the mod to change this? I like the Moon Elves, but this one detail makes them far too strong for me to consider allowing them in their current state. 

With Simply Swords + Better Combat, an Iron cutlass has 6 damage, 2 attack speed, and 2,5 attack range. An iron sword does the same damage while swinging at a slower 1.6 speed. Not only does the cutlass get boosted to 9 damage, more than any axe before netherite, but it swings _twice as fast_ as a diamond axe, but with a stealth break gurantees an instant kill versus practically anything that isn't wearing Protection-enchanted armor. 

Keep in mind, the only difference between the recipe for a cutlass and a sword in cost is a single iron nugget. This is insane. I hate this and I want to turn it off without completely gimping Moon Elves. Is there a way for me to change the mod/mods I have so cutlasses won't receive this bonus without digging into .jars? If not, how would I go about changing this in that way?

**Comment by muon-rw** [comment]
Cutlasses should not be receiving dagger bonuses - Which version are you playing? 

By default this will only include a melee weapon whose item id contains "dagger", "knife", "sai", or "athame": 
https://github.com/muon-rw/Medieval-Origins-Revival/blob/4c6e4dc38b687a24f2d2386da6b884a4b38f6cfe/forge/src/main/java/dev/muon/medievalorigins/condition/ModConditions.java#L59-L63

or is in this item tag (which you can add to manually): 
https://github.com/muon-rw/Medieval-Origins-Revival/blob/1.20.1-multiloader/common/src/main/resources/data/medievalorigins/tags/items/daggers.json

**Comment by ghotiPhoti** [comment]
i'm playing `MedievalOriginsRevival-6.4.6+1.20.1-fabric` on 1.20.1 Quilt.
BetterCombat is 1.8.6, Simply Swords is 1.56.0.

the effect is given to every cutlass in the mod, including one added by Mythic Metals(0.19.9). 
It also affects every sai, dagger, and knife in the modpack, even a couple of unique blades that don't have any of those words in the name: Soulstealer and Emberlash.

This is especially weird because as an Ogre, using the unique greataxes (Soul Pyre, Molten Edge, Livyatan) from the same Simply Swords mod doesn't give the Ravager bonus, but all the standard axes/greataxes do.

Meanwhile Valkyrie seems to be just fine. Heavenly Implement affects spears, glaives and halberds, even the unique polearms. Even the Sword on a Stick gets boosted 😭😭😭

**Comment by ghotiPhoti** [comment]
I haven't figured out how to fix the cutlasses yet, but in the meantime I've made this as part of a datapack I'll be using to tweak/fix origin abilities in general
[axes.json](https://github.com/user-attachments/files/17452402/axes.json)

**Comment by muon-rw** [comment]
> i'm playing `MedievalOriginsRevival-6.4.6+1.20.1-fabric` on 1.20.1 Quilt. BetterCombat is 1.8.6, Simply Swords is 1.56.0.
> 
> the effect is given to every cutlass in the mod, including one added by Mythic Metals(0.19.9). It also affects every sai, dagger, and knife in the modpack, even a couple of unique blades that don't have any of those words in the name: Soulstealer and Emberlash.
> 
> This is especially weird because as an Ogre, using the unique greataxes (Soul Pyre, Molten Edge, Livyatan) from the same Simply Swords mod doesn't give the Ravager bonus, but all the standard axes/greataxes do.
> 
> Meanwhile Valkyrie seems to be just fine. Heavenly Implement affects spears, glaives and halberds, even the unique polearms. Even the Sword on a Stick gets boosted 😭😭😭

Yeah, as you can see in the links from my other reply the soulstealer and emberlash are on the manual list, while every other dagger, sai, and knife should be picked up automatically by the regex. Heavenly implements was also manually tweaked to include unique polearms. 


I've found the source of the issue, however. The deprecated AutoTag class still references simply swords cutlasses directly (I remember now that another user *specifically* requested they be included in the dagger bonus). 
https://github.com/muon-rw/Medieval-Origins-Revival/blob/aff84fd1ea8b16937586c00550185f40f959cbdd/fabric/src/main/java/dev/muon/medievalorigins/ModTags.java#L32 

This tagging will be removed shortly anyway, but for now you should be able to override its behavior by setting your `daggers.json` tag to `"replace": true` 



P.S. If you have changes to make to inclusions (such as the unique axes), I heavily encourage submitting a PR so all can benefit :)

**Comment by ghotiPhoti** [comment]
id love to make a pr for it (and a couple other things) but i don't really know how to xD
