### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by ElasticKnife** [muon-rw/Medieval-Origins-Old#159]
Crash on startup occurs when Medieval Origins is added, but loads to menu when taken out.
[https://mclo.gs/M9dJRxW](https://mclo.gs/M9dJRxW)

**Comment by muon-rw** [comment]
Apugli has a mixin conflict with some mod in your list.

If I had to guess, it’s being caused by Palladium or Essential.

**Comment by muon-rw** [comment]
Closing as stale
