### ISSUE TITLE
Arachnae isn't a carnivore (+Pull Request)

### ISSUE THREAD

**Issue by ghotiPhoti** [muon-rw/Medieval-Origins-Old#162]
Title. Thought it might be an issue on my end but it persists even on a new installation with nothing but this mod and all dependencies. Will post a PR once I figure out how to properly make one.

**Comment by gaobro** [comment]
Having the same problem, is not on your end o/ is there a way to temporarily fix this with a datapack?

**Comment by ghotiPhoti** [comment]
yeah, i've got a quick fix for it right here. 
[§cArachnae §7quick fix.zip](https://github.com/user-attachments/files/17612221/cArachnae.7quick.fix.zip)
it was pretty much just a single line of code missing in a .json

**Comment by ghotiPhoti** [comment]
@muon-rw pwetty pwease merge 👉👈🥺

**Comment by muon-rw** [comment]
Hi, thanks for catching this.

@ghotiPhoti Looks like you didn’t actually submit the PR, you can do so from your repository page

**Comment by ghotiPhoti** [comment]
ahhh ok, gotcha. just submitted it as an actual PR i think.

**Comment by ghotiPhoti** [comment]
DID I DO IT BACKWARDS 😭

**Comment by ghotiPhoti** [comment]
ok, i see what I did wrong, let me try this again lmao

**Comment by ghotiPhoti** [comment]
It wouldn't let me do it from the previous repository I had because it seemed that the edit I made was gone from it so I just tried again and completed the process. Sorry for the hassle, i suck at this website lmao.

Anyway, this should resolve this issue.
https://github.com/muon-rw/Medieval-Origins-Revival/pull/164
