### ISSUE TITLE
Visual Bug when using Epic Fight 

### ISSUE THREAD

**Issue by cjusino13** [muon-rw/Medieval-Origins-Old#163]
![image](https://github.com/user-attachments/assets/3528329e-8e2e-448f-b560-8dd92ce00b3e)

Recently when I was testing out my modpack after a small hiatus, I noticed a visual bug with the mod and epic fight. This wasn't an issue before, and I was wondering if there was any know fix to it.

**Comment by cjusino13** [comment]
Screenshot provided is using the Dwarf origin, this only happens with the smaller races.

**Comment by muon-rw** [comment]
No interest in supporting bugs caused by Epic Fight, sorry.
