### ISSUE TITLE
Tranformer rendering error

### ISSUE THREAD

**Issue by Grood01** [muon-rw/Medieval-Origins-Old#169]
When I enter into a new world the game crashes after opening the origins menu, its a transformer rendering error, I think it trys to rednder the player at differnet height or width for the player model and crashes.

**Comment by muon-rw** [comment]
Please send the crash report?

**Comment by Grood01** [comment]
[2024-11-30-6.log.gz](https://github.com/user-attachments/files/17967360/2024-11-30-6.log.gz)

**Comment by muon-rw** [comment]
Apugli seems to be incompatible with Essential. Given the business and development practices of Spark Universe I won't fix this. 

I would recommend trying something like https://modrinth.com/mod/e4mc
