### ISSUE TITLE
Archers [RPG Series] Compatibility

### ISSUE THREAD

**Issue by normalgithubuser11** [muon-rw/Medieval-Origins-Old#18]
Daedalus made a new mod for archer classes and I would appreciate it if the wood elf passive ability could be compatible with the new bows in that mod. Also, the wood elf bow passive ability is pretty broken, a little nerf on the damage would be good too :D or, if there is another way for me to alter the damage and add compatibilities on my own through the files, let me know.

**Comment by muon-rw** [comment]
Are you playing 5.2.1? It should already be compatible. 

As far as nerfs, that was also done in 5.2.1 if you have Zenith - I may also nerf the non-compat version as well.

**Comment by muon-rw** [comment]
Closing as already implemented, feel free to reopen if something is missing.
