### ISSUE TITLE
Forge 1.16.5, 1.18.2, 1.19.2

### ISSUE THREAD

**Issue by Filippide8864** [muon-rw/Medieval-Origins-Old#19]
A forge version can be created in versions 1.19.2 and 1.18.2

**Comment by muon-rw** [comment]
I most likely won't backport. 
Origins Forge on older versions of Minecraft is pretty buggy, so unless that changes I’d rather spare myself the headache of working around it.

While this project is abandoned, it does at least work on older Forge versions:
Collections of Singiro: https://www.curseforge.com/minecraft/mc-mods/collection-of-singiro
