### ISSUE TITLE
Banshee Shriek Not Working (1.20.1, forge versions)

### ISSUE THREAD

**Issue by Eclipse0227** [muon-rw/Medieval-Origins-Old#20]
- installed via downloading the file itself and putting it manually into the mods folder vs direct download via CurseForge
 - Tried using different key binds
 - tried while in front of a mob, did no damage, and did not activate strength
 - tried only using bare necessary mods for it to work 
 - tried reloading the banshee origin via the origin orb
 - tried using other 1.20.1 versions of this mod
 - other users (my friends) have replicated the same issue
 - using forge 1.20.1 v 47.2.0 in the java Minecraft launcher

Steps to replicate:
1. create a new world 
2. choose the Banshee origin
3. once the cooldown for the shriek has finished, press the key bind to toggle the primary power
4. note that no shriek is toggled, no strength is given, and no mobs were damaged along with the lack of the cooldown bar appearing

      when you spawn in and choose the banshee origin, the bar loads and disappears as intended, when you press the key bind to activate the shriek nothing happens and the cooldown bar does not appear (which makes sense).  I have not found a way to get the shriek to work. I am not sure if you were aware of this but i figured it would be good to let you know.

**Comment by muon-rw** [comment]
Thanks for the detailed report, I can take another look at this. 

Can you send your latest.log file as well? If you're concerned about personal information you can use https://mclo.gs

**Comment by Eclipse0227** [comment]
https://mclo.gs/30WXt10

**Comment by Eclipse0227** [comment]
https://mclo.gs/30WXt10
mb accidently closed the issue (i don't use github nearly enough to know how it works lmao)
I also cleared out all the config files i had but it still doesn't seem to work. just tested it in a new world i just made.

**Comment by muon-rw** [comment]
Fixed in dev
