### ISSUE TITLE
Pixie Origin crashes game when ascending scaffold.

### ISSUE THREAD

**Issue by coldReactive** [muon-rw/Medieval-Origins-Old#21]
When holding space to ascend in scaffold, the game will crash. This is in the Modpack Medieval MC; Using MultiMC. I'm using the version from Modrinth, which is MMC2 v1, on Minecraft 1.20.1

The Modpack Admins said to report it to you rather than them, despite the issue not happening when this mod is on its own.

[crash-2023-11-22_14.49.42-server.txt](https://github.com/muon-rw/Medieval-Origins-Revival/files/13444739/crash-2023-11-22_14.49.42-server.txt)
[crash-2023-11-22_14.58.32-server.txt](https://github.com/muon-rw/Medieval-Origins-Revival/files/13444740/crash-2023-11-22_14.58.32-server.txt)
[latest.log](https://github.com/muon-rw/Medieval-Origins-Revival/files/13444741/latest.log)

And the evidence to show it works on its own:

![image](https://github.com/muon-rw/Medieval-Origins-Revival/assets/1313673/8d247cea-5371-4135-a201-c4c975ab0959)
![2023-11-22_16 26 27](https://github.com/muon-rw/Medieval-Origins-Revival/assets/1313673/147bed53-69e6-4ce8-b4e4-b06c2e0101e6)

And the modpack admin saying to report it here:

![image](https://github.com/muon-rw/Medieval-Origins-Revival/assets/1313673/4a9341a1-15ea-406e-9206-9ae2465c1b72)

**Comment by muon-rw** [comment]
The crash report you posted is a supplementaries bug, update to 2.6.30 or newer
https://github.com/MehVahdJukaar/Supplementaries/issues/840

I can't reproduce any issues with the pixie in scaffolding specifically. Let me know if you continue to have issues after updating.

**Comment by muon-rw** [comment]
_no, i didn't realize that was your issue when i linked it_
