### ISSUE TITLE
Medieval Weapons mod compatibility

### ISSUE THREAD

**Issue by Flyvee** [muon-rw/Medieval-Origins-Old#25]
With the moon elf origin, the dagger from the medieval weapons mod (https://www.curseforge.com/minecraft/mc-mods/medievalweapons) is not in there, can you please add it?

**Comment by muon-rw** [comment]
Sure, should be easy to add.

**Comment by muon-rw** [comment]
No longer necessary with https://github.com/muon-rw/Medieval-Origins-Revival-Forge/commit/3081c10877bf47ffe7c5137b666ce79d5f7c1d43 will port back to fabric soon
