### ISSUE TITLE
Pixie Flight is annoying.

### ISSUE THREAD

**Issue by toErIpNid** [muon-rw/Medieval-Origins-Old#30]
When using the Pixie Origin with the 6.0.0 update I would much rather have them go back to just using Levitation, the jumping flight they have now both feels really bad to play with and is too slow compared to the Fae which has much better flight.

**Comment by muon-rw** [comment]
Appreciate the feedback.
Can you clarify what you mean by “too slow”? They should be faster in most cases.

**Comment by toErIpNid** [comment]
They're not, their flight ends up being similar to them jumping up block by block and lacks mobility. It takes forever to get anywhere using it.

**Comment by muon-rw** [comment]
So mostly upward velocity? I can think of a couple changes that could happen:
1. Jump height could be increased, and fall speed decreased slightly, to make the jump more "floaty."
2. The "hold-in-place" levitation could be switched back to a mix of the current and the old, allowing you to float up or hold-in-place
3. An active dash ability (maybe something like crouch+jump) that propels you much further, potentially with a resource limit. It could also be used to dash forward to traverse longer distances.

I'll probably do a mix of 1 and 3, but I'll playtest it a bit more. Feel free to suggest anything else.

**Comment by Voidpexx** [comment]
Please just give pixies creative flight. levitation just makes them worse fae and this new system feels extremely jank. I'm assuming you believe this would be unbalanced and is probably why you haven't done it. but not being able to equip a chest plate is a massive downside that i feel balances it out. you literally cannot use the most protective piece of armour; if you are wearing prot 4 diamond armor your effective hp goes from 66 down to 44 just from unequipping your chest plate AND on top of that you have massively reduced hp.

**Comment by toErIpNid** [comment]
No, Pixie flight is both slow vertically, horizontally, and bounces around too much. It's just a really bad method of flight altogether and feels bad to use. Please just do what the other commenter said and just give them creative flight. They already have half the health of a Human, that's the biggest downside anyone can have, on top of not being able to wear a chest piece. They need good mobility to justify having such low health.

**Comment by muon-rw** [comment]
It should be noted that pixies can wear leather chestplates. 

If I do add creative flight, I think it would be best to restrict them from wearing chestplates entirely again. 

That said, I think a non-creative, dash-based flight system will be a lot more fun (and even more useful), if done right. I'll have an update to try out soon; unfortunately I'm running into several underlying bugs in Origins Forge so it's much more infuriating than expected.

**Comment by toErIpNid** [comment]
Leather armor gives so little protection it doesn't make much of a difference at all. 

There is no way a dash-based system will be more useful than creative flight, especially in regards to building.

**Comment by muon-rw** [comment]
If you want Pixies to have creative flight you are welcome to do so with a datapack. 

If your interest is optimal creative building I encourage you to use the fantastic and very obscure “gamemode” feature.
