### ISSUE TITLE
Is there a way to add the moon elf rouge bonus to other mods weapons?

### ISSUE THREAD

**Issue by Francesco-Palombo** [muon-rw/Medieval-Origins-Old#31]
I wanted to ask it in curseforge, but the comment section is still broken.

**Comment by muon-rw** [comment]
Sure, you could add them to the medievalorigins:daggers item tag. 
Though I'm curious, which mods do you plan to add? I don't mind supporting it natively.

**Comment by Francesco-Palombo** [comment]
Thanks for the info!
To answer your question:
- Aquamirae (Dagger of Greed, idk for the other weapons some seems like a dagger but at the same time a sword)
- The Graveyard (Bone Dagger)
- MC Dungeon and Dragons (Eternal Knife, Soul Knife? idk about this 'cause its a dagger but two handed, The Last Laugh)
- Bakery (Bread Knife Its seems funny to deal extra damage with it like with farmer delight)
- Knaves Needs (all the sai type)

You don't have to add all of them, this is what i was thinking. Of course if you dont agree with something dont mind my message.

Thanks for your time and your mod is great!

**Comment by muon-rw** [comment]
No I agree, all knives and daggers should probably be included. 

However I'm somewhat confused because all of these from what I remember should *already* be included, with the exception of the Aquamirae dagger and the Knaves' Needs sai's. I'll take another look at it.

Which version are you playing?

**Comment by Francesco-Palombo** [comment]
Im playing the 5.2.1 fabric

**Comment by muon-rw** [comment]
Yup, looks like I added them to Forge but not Fabric - I'll be porting back all of the reworks from Forge to Fabric shortly anyway, and this will be included.

**Comment by Francesco-Palombo** [comment]
Thanks!!

**Comment by muon-rw** [comment]
All daggers/knives should be supported automatically with https://github.com/muon-rw/Medieval-Origins-Revival-Forge/commit/3081c10877bf47ffe7c5137b666ce79d5f7c1d43 - Still planned to port back to fabric
