### ISSUE TITLE
Origins Resize Doesn't Work & Dwarf NV/Blindness not applying

### ISSUE THREAD

**Issue by X-Hellfire-X** [muon-rw/Medieval-Origins-Old#38]
When I run a singleplayer world selecting origins, they dont resize, and the dwarf doesnt get blindness in sunlight even without a helmet, nor do we have night vision in the dark.

**Comment by muon-rw** [comment]
For resizing: Do you have the Pehkui mod?

Can't reproduce the other issues. What version are you playing?

**Comment by X-Hellfire-X** [comment]
yes i do. 
im playing on 1.20.1

**Comment by muon-rw** [comment]
Which mod version?

**Comment by X-Hellfire-X** [comment]
6.1.1

**Comment by muon-rw** [comment]
I can't reproduce this in any scenario on newer versions - if it's still happening after updating, feel free to reopen
