### ISSUE TITLE
[Forge] [Bug] [Compat] Mermod integration isn't obvious / doesn't activate

### ISSUE THREAD

**Issue by goldrat1** [muon-rw/Medieval-Origins-Old#56]
The description claims this mod has 'Built-in integration for Mermod' but either this integration doesn't exist, isn't obvious to users, or isn't working. Presumably the mermaid tail trait from Mermod is meant to activate when either the Merling or Siren enters water, but neither of them have this trait listed nor do they activate when in water.
Would love to see this working as attempts to get Mermod to work with Origins through datapacks seems to broken at the moment as well.

**Comment by muon-rw** [comment]
It uses the Origins integration that Mermod already has, but it looks like they don't maintain this functionality on Forge. 

I'll specify that it's Fabric only for now, but will look into implementing this at some point.

**Comment by muon-rw** [comment]
Will be added in 6.4.5

**Comment by Ikerrd2115** [comment]
hey mermod is still crashing on forge or at least in my case i`m playing in version 6.4.5 

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class dev.muon.medievalorigins.power.factory.MermodTailPowerFactory cannot be cast to class io.github.thatpreston.mermod.forge.compat.origins.TailPowerFactory (dev.muon.medievalorigins.power.factory.MermodTailPowerFactory is in module medievalorigins@6.4.5+1.20.1-forge of loader 'TRANSFORMER' @638977e0; io.github.thatpreston.mermod.forge.compat.origins.TailPowerFactory is in module mermod@3.0.1 of loader 'TRANSFORMER' @638977e0)

idk what is causing the error
