### ISSUE TITLE
[Forge Only?] Fae active ability missing keybind.

### ISSUE THREAD

**Issue by IronShears** [muon-rw/Medieval-Origins-Old#57]
So, I noticed pretty quickly that the Fae origin didn't have the levitation ability it was supposed to and did some more snooping. When you hover over the "A" in the GUI it says the key you're supposed to press is [], whereas most of the other primary abilities say [G] for me. I went back and checked all the other origins and Fae seems to be the only one that has this issue.

Now, I'm not exactly familiar with coding Origins, but after looking through the levitation.json files and comparing it to the secondary ability for the banshee which is also "origins:multiple", it looks like the "key" part is missing the outer brackets.

This is what the Levitate key in the .json looks like for Fae. No outer bracket that looks like "key": { }. This ability is not accessible in the game.
![image](https://github.com/muon-rw/Medieval-Origins-Revival/assets/71862623/d3f244dd-5d4d-4e25-a18e-c09ab6775cca)

And this is the Banshee's. It has that outer bracket. This ability works just fine.
![image](https://github.com/muon-rw/Medieval-Origins-Revival/assets/71862623/0e744fb5-8765-4321-9bc5-3d60302fd05e)

**Comment by muon-rw** [comment]
Yup, “key” in the base of a power needs to be an object, not a string. Thanks for the report. Which version are you playing?

**Comment by IronShears** [comment]
1.20.1 forge. Looks like 6.2.5.
![image](https://github.com/muon-rw/Medieval-Origins-Revival/assets/71862623/b8be6f36-a622-4532-8621-345b0d0f65d6)

**Comment by muon-rw** [comment]
key being a string instead of an object seems to cause no issues on Fabric. I'll change it though.

**Comment by muon-rw** [comment]
I actually can't reproduce this as an issue - the keybinding loads fine and the power works on Forge even if it's a string, not an object. 

Changed it to an object anyway.
