### ISSUE TITLE
advice/question

### ISSUE THREAD

**Issue by DesuPinkgit** [muon-rw/Medieval-Origins-Old#58]
Certain orgins excel with certain weapons/armor. How is this detected and how could i add that function to something else. For example the goblin gets buffs using gold armor and items how could i tell the game the item is gold. Or additionally moon elf likes daggers and knife. How could I tell the game that the item is classified as a dagger to get the buff?

**Comment by muon-rw** [comment]
It varies slightly by version, but in all cases there should be a fallback item tag: `medievalorigins:daggers` or `medievalorigins:golden_armor` 

You could add to these with a datapack, the path should be `data/medievalorigins/tags/items/daggers.json` or `data/medievalorigins/tags/items/golden_armor.json`

That said, on Forge most should already be being detected by item id, and on Fabric I'll have a similar detection implemented soon.

**Comment by muon-rw** [comment]
Added in 6.3.0
