### ISSUE TITLE
Fae attraction remains with Orb of Origin use

### ISSUE THREAD

**Issue by AENykorak** [muon-rw/Medieval-Origins-Old#61]
ATM9 v0.2.54
Minecraft 1.20.1
Medieval Origins Revival v6.2.5

On switching from Dwarf (potentially any) to Fae, then back, Fae attraction was not removed.
Only way to turn off was to go into config and turn off Fae attraction. This turned it off for the Dwarf.
No visible effect in the character. Perhaps other mod interaction issues, but havn't seen any other mod interaction issues yet.

**Comment by muon-rw** [comment]
Doesn’t look like a mod interaction but rather a formatting error on my part. Will fix next update.

**Comment by AENykorak** [comment]
Turning off the effect in the config did not work.
Do you know of another way to get rid of the attraction effect short of deleting the player data?

**Comment by muon-rw** [comment]
Yes, for now just use `/scale reset pehkui:visibility` (might need to put a username or target selector in there somewhere, not 100% sure on the command format)

**Comment by AENykorak** [comment]
Seems like it worked. Was followed by the username.\
Thanks. Was getting overwhelming lol
