### ISSUE TITLE
[Incompatibility] RPG Difficulty causes Summoned Zombies to no longer spawn

### ISSUE THREAD

**Issue by thrasos-dev** [muon-rw/Medieval-Origins-Old#62]
Issue regarding Revanant Origin as described by LastMarauder:
> Hello, Muon! I'm afraid today's issue has been rather baffling so far. 
>
>The Revanant Origin seems to be having a problem. In just about every other way, it's in top shape, but when I'm in Solo on Fantasy MC, and I try to make a zombie...nothing! Everything else works fine, Skeletons, Zombie Horses, eating skulls, but not the base melee zombie! 
>
> We at Pixel Dream Studios have been working on including Medieval Origins into Fantasy MC, to see your works enjoyed by as many as possible! And would love to help, seeing as a number of fans are having the same issue. To assist, we've included a log of the instance occurring, and hope to provide aid in seeing the matter resolved.
>
> Thank you for reading this! -The Pixel Dream Studios Team.

[latest.log](https://github.com/muon-rw/Medieval-Origins-Revival/files/14898718/latest.log)

**Comment by muon-rw** [comment]
Hi Kyber, looks like the issue is happening here:
`java.lang.IllegalArgumentException: Duplicate id value for 27!
	at net.minecraft.class_2945.method_12784(class_2945.java:81) ~[client-intermediary.jar:?]
	at dev.muon.medievalorigins.entity.SummonedZombie.method_5693(SummonedZombie.java:214) ~[medievalorigins-6.3.0+1.20.1.jar:?]`
	
Which means I've done something *really* silly and probably easily fixable. 
Will take a look at this soon!

**Comment by muon-rw** [comment]
It looks to be a mod compat issue - maybe something else is assigning FOLLOW_RANGE automatically to all Zombies? 

I'll try to narrow it down.

**Comment by muon-rw** [comment]
It's caused by [this mixin](https://github.com/Globox1997/RpgDifficulty/blob/1.20/src/main/java/net/rpgdifficulty/mixin/entity/ZombieEntityMixin.java). 

Defining synched entity data in that mixin causes SummonedZombies' attempt to add a tracked Owner UUID result in this duplicate id value error. 

Not really sure what to do about that, though...

**Comment by muon-rw** [comment]
Fixed in 6.3.1

**Comment by KevzCz** [comment]
Noice :Đ good work
