### ISSUE TITLE
Projectile Damage Attribute is used but not bundled or marked as a required dependency 

### ISSUE THREAD

**Issue by Asdedo** [muon-rw/Medieval-Origins-Old#64]
I dont quite know how to properly upload a report, but on a minecraft server im trying to make with my friends, whenever you use the revenant origin, after crafting your first undead, be it a zombie or a skeleton, if you have less than the required ammount of materials (bones or rotten flesh) in your hand, and press the ability key, it still summons an undead at no cost, also allowing me to spam summoning and making it quite unbalanced.

**Comment by muon-rw** [comment]
Thanks for the report, there are multiple checks in place to ensure this kind of thing doesn’t happen so that’s a weird one. 

Can you be a bit more specific about how to summon future creatures for free? Does it require holding down the key?

**Comment by Asdedo** [comment]
Alright so, at the first step, im holding 5 bones in my hotbar, i press "G" to activate the ability, 4 bones are spent to summon 1 skeleton, then with 1 remaining bone in my hotbar, if i press "G" again, it summons another skeleton, without even spending the one bone in my hotbar, and allowing me to press "G" for the ability again and again.
![2024-04-09_16 44 07](https://github.com/muon-rw/Medieval-Origins-Revival/assets/82228309/4be0fb00-eb6c-4fe3-9b74-cfe01057d91f)

**Comment by muon-rw** [comment]
It seems to be an underlying bug and not an issue with the power itself.

That said, there’s another place I can add a sanity check to ensure this won’t happen, seems like I didn’t do this with base skeletons. Will do so next update.

**Comment by Asdedo** [comment]
it happens with the zombies as well

**Comment by muon-rw** [comment]
Yeah, by that I just meant that the “base” entity for each type has no check in place to ensure the power was actually started with 4 flesh/bone or not (even though that shouldn’t be possible), they just run if every other check fails. 

I’ll make sure zombies get the same double-check.

**Comment by Asdedo** [comment]
I just checked again, it actually seems it goes beyond that, cuz i tested again and noticed that when i use the 5 bones in my hotbar, they arent actually spent, so when you open the inventory and place the "1 bone" anywhere else, it turns back to being 5

**Comment by muon-rw** [comment]
This is probably the only issue then.  There should be no reason a desync happens like that. Thanks for looking into it.

**Comment by Asdedo** [comment]
idk why this happens, but id just like to know if theres a way to fix it or something, and maybe if it is some other mod clashing in some way with this one, here's the modlist im currently running.
![Captura de pantalla 2024-04-09 175424](https://github.com/muon-rw/Medieval-Origins-Revival/assets/82228309/12aae680-eac9-4f8a-be33-b5cbe22f9b27)

**Comment by muon-rw** [comment]
Can you send your latest.log from when you summoned a zombie or skeleton?

**Comment by Asdedo** [comment]
[latest.log](https://github.com/muon-rw/Medieval-Origins-Revival/files/14924633/latest.log)

**Comment by Asdedo** [comment]
at the end i started spamming zombies

**Comment by muon-rw** [comment]
It actually looks like the root cause of this issue is likely Projectile Damage Attribute not being present, that’s my mistake as I meant to bundle it. 

For now, installing that (or Archers - RPG Series) will probably fix the issue. If you do, make sure to remove it next update, as the mod is being deprecated soon.

**Comment by Asdedo** [comment]
Oh, but dw i mean to play in 1.20.1 anyways, love this mod and kudos for your work !, i used to play medieval mc a long while ago and your port saved me the effort of having to look for a proper necromancy mod (there aint much, almost none for 1.20). Thanks for all the help as well !

**Comment by muon-rw** [comment]
I would recommend Simply Skills as another source of necromancy- The dev is doing a great job with it and the two mods should work well together.
