### ISSUE TITLE
Ogre origin gets hyper speed when in contact to walls

### ISSUE THREAD

**Issue by Asdedo** [muon-rw/Medieval-Origins-Old#65]
Its me again... For some reason, the Ogre when in contact to a wall gets an insane ammount of acceleration towards where it is moving

https://github.com/muon-rw/Medieval-Origins-Revival/assets/82228309/0d15d1f5-09fc-4d90-b3af-46ed3a269354

**Comment by muon-rw** [comment]
If I had to guess, this is an issue with how Pehkui calculates their step height. I’ll do some digging.

**Comment by Asdedo** [comment]
dont know if it helps but here is the Latest.Log after i tried it again in other world
[latest.log](https://github.com/muon-rw/Medieval-Origins-Revival/files/14926341/latest.log)

**Comment by muon-rw** [comment]
Most likely this is caused by Valkyrien Skies. Does removing it fix the issue?
