### ISSUE TITLE
Flying into water with Icarus wings forces server disconnect 1.20.1

### ISSUE THREAD

**Issue by ThatPocket** [muon-rw/Medieval-Origins-Old#66]
Flying into any body of water with Icarus wings equipped will force a disconnect due to an "Internal Server Error," regardless of what origin you have selected
Running Fabric 1.20.1

**Comment by muon-rw** [comment]
Which version of Icarus?

**Comment by muon-rw** [comment]
Can't reproduce since 1a22395, most likely fixed.
