### ISSUE TITLE
Elytra doesn't work as Pixie

### ISSUE THREAD

**Issue by LordFirecat** [muon-rw/Medieval-Origins-Old#67]
When I tried to activate the elytra as the pixie, the space bar input instead was used to jump.  Would there be a way to make the pixie only jump infinitely if hovering or not wearing an elytra, or maybe add a keybind to trigger elytra flight using the Origins Extra Keybinds mod?

**Comment by muon-rw** [comment]
I’ll most likely add a toggle for whether you jump or switch to fall flying.

**Comment by muon-rw** [comment]
Closing as duplicate in favor of #76
