### ISSUE TITLE
[Forge] [Suggestion] Making the wall-climbing ability of the Archnae toggleable

### ISSUE THREAD

**Issue by goldrat1** [muon-rw/Medieval-Origins-Old#68]
Hi, I'm using the Arachnae class and I constantly find myself snagging on walls when I'm trying to move around as the Climbing ability isn't toggleable like it is for the base mod Arachnid origin. I think it'd make Arachnae a bit more accessible if there was a keybind to disable the climbing ability for the Archanae Origin.

**Comment by muon-rw** [comment]
It’s also toggleable for the Alfiq but I just never added this retroactively. Thanks for the heads up
