### ISSUE TITLE
Siren Song(?) causes lag when hitting entities

### ISSUE THREAD

**Issue by goldrat1** [muon-rw/Medieval-Origins-Old#69]
Hi there,
I'm running a fairly heavy modded server and we've noticed that every now and then when one of our players is using the Siren Origin and they hit something, the whole server freezes for a few seconds and runs many ticks behind. This also evidently happens in singleplayer.
Through testing we've found that this happens every 45 seconds, which is the cooldown for the Siren Song. I can only presume that this is the reason for the lag spike.
This really needs a fix as it completely stops the server if someone's using the Siren origin! We're using a lot more mods, most of which are listed in this latest.log. Nothing shows up in the log when this happens.
[latest.log](https://github.com/muon-rw/Medieval-Origins-Revival/files/15009966/latest.log)

**Comment by muon-rw** [comment]
Siren Song has been reworked on Fabric, it will be ported back to Forge soon.

**Comment by muon-rw** [comment]
Fixed in 6.4.0, which will release within the next week
