### ISSUE TITLE
Alfiq origin crashes game when attempting to pickpocket villagers 

### ISSUE THREAD

**Issue by goldrat1** [muon-rw/Medieval-Origins-Old#70]
Hi there,
Whenever someone with the Alfiq Origin tries to pickpocket a villager, the second time they pickpocket the same villager the game crashes to desktop. The first time they manage to get an emerald, but if they try it again the game crashes.
Crash log linked below:
[crash-2024-04-18_13.05.09-client.txt](https://github.com/muon-rw/Medieval-Origins-Revival/files/15019442/crash-2024-04-18_13.05.09-client.txt)
This might be an incompatibility with one of the many other mods we have, they're listed in the crash report.

**Comment by muon-rw** [comment]
Looks like https://github.com/muon-rw/Medieval-Origins-Revival/blob/e37a8a1735649ad5760389a3cb48303a74b738a5/src/main/resources/data/medievalorigins/powers/alfiq/pickpocket.json#L7-10 just needs a damage_type. Thanks for the report.

**Comment by muon-rw** [comment]
Fixed in #b0a18bd
(It may be awhile yet before this sees a Forge release)
