### ISSUE TITLE
Summoned Zombies turn into enemy drowned

### ISSUE THREAD

**Issue by Asdedo** [muon-rw/Medieval-Origins-Old#71]
Time and time again, i tend to spend a good quantity of rotten flesh into boosting the Revenant ability to summon a stronger zombie, only to then see the zombie fall into a measly 2 block deep lake and become a drowned that attacks me, spawns with the normal stats of a drowned at least, but still, i lose my super minion beacuse of its AI.

I dont know if that is intended or not, but id like to know if theres anything to do about it. That or if i may suggest a function to right click minions so they stand still, like with a tamed dog, cuz otherwise, they are constantly trying to follow me, and managing their pathfinding and for where i am walking becomes a struggle, would be cool to set them in place as guards. Like maybe skeletons standing still and acting like sentry's for defence.

**Comment by Asdedo** [comment]
also, would like to ask if this is ok
Snow golem has been all day trying to murder him
![image](https://github.com/muon-rw/Medieval-Origins-Revival/assets/82228309/7cb5d752-8443-4f99-880a-39a2326e1847)

**Comment by muon-rw** [comment]
They should probably be avoiding or at least swimming in water, I'll take a look at that. Golems wanting to target them sounds normal.

**Comment by Asdedo** [comment]
Oh, i also wanna mention it, now that ive noticed again. There is supposed to be a bar that charges up when i recieve damage, right ?, the one that allows me to steal life from enemies when charged. It always appears black and empty whenever i get hit, just like in the image, so i never know if i have more than one life stealing hit or not.

**Comment by muon-rw** [comment]
Yeah it’s a bit hard to see, I’ll change the bar design

**Comment by muon-rw** [comment]
Fixed in 6.4.0, which should release within the next week
