### ISSUE TITLE
[FABRIC 1.20.1] Not working with latest version of Spell Power Attributes

### ISSUE THREAD

**Issue by gamerpotion** [muon-rw/Medieval-Origins-Old#72]
Hi, Medieval Origins isnt working when Spell Power Attributes is updated to its latest version - https://www.curseforge.com/minecraft/mc-mods/spell-power
please could you update.

**Comment by KevzCz** [comment]
+1 :Đ

**Comment by muon-rw** [comment]
Updated in 6.3.1!
