### ISSUE TITLE
Revenant Illagers

### ISSUE THREAD

**Issue by Taxete** [muon-rw/Medieval-Origins-Old#73]
Illagers still attack with revanant class selected on 1.20.1 version on forge, i've also tried multiple worlds and they still attack with revenant class selected.

**Comment by muon-rw** [comment]
Always, or only if you attack them first? 

A latest.log would be helpful too

**Comment by Taxete** [comment]
always without attacking them first, is it because of perhaps having another origins mod on?

**Comment by Taxete** [comment]
![ASDASDASDASD](https://github.com/muon-rw/Medieval-Origins-Revival/assets/168150934/8b9aa067-7cd8-43c8-8366-873921f0d8be)
I think one of the extra ones is making it incompatible

**Comment by Taxete** [comment]
its working now that I turned off fallen origins

**Comment by KiraKayn** [comment]
> its working now that I turned off fallen origins

Will be fixed in the next update of Fallen Origins.
