### ISSUE TITLE
Improve Pixie flight

### ISSUE THREAD

**Issue by LuigiTP** [muon-rw/Medieval-Origins-Old#76]
in the latest version (6.2.5) if you choose pixie origin and get any other method of flying, like creative mode or other mods items like botania's Tiara, the pixie's flight mechanic overrides them. Hopefully this is an easy thing to implement.

Though this is not the main point of this issue i would like to add a suggestion:
The flight mechanic itself is a bit annoying to use, there is no smooth control whatsoever if you intend to build , so something like Shift to go down while in hover would improve it dramatically as constantly having to adjust the height feels bad, it is also weird that you are able to go up but not down while hovering. If this Shift to lower oneself is too close to creative flight then maybe changing the hover completely to a slower creative flight for balance purposes would be better?

**Comment by muon-rw** [comment]
I wouldn’t mind adding a way to smoothly fly downward, height control  with the existing flight has definitely been a bit tricky in my experience. 

I’ll probably have it apply when shift is held like you suggest, same as creative flight. Will have to do some testing with it.

Adding a check for existing creative flight too should be no issue

**Comment by muon-rw** [comment]
Will be implemented in 6.4.0
