### ISSUE TITLE
Size not changing

### ISSUE THREAD

**Issue by 9182736450typist** [muon-rw/Medieval-Origins-Old#77]
I tried starting worlds as both a Fae and a Pixie, and even by using a command or starting the world in survival mode, my size is stuck at default not allowing me to fit through small gaps without sneaking/crawling.

Version: 1.20.1 forge, mod version 6.2.5

**Comment by muon-rw** [comment]
Do you have Pehkui installed? It doesn’t always get automatically downloaded, even though it should be marked as such.

**Comment by 9182736450typist** [comment]
Yes, I am still normal size.

**Comment by 9182736450typist** [comment]
Scratch that, it works in survival mode
