### ISSUE TITLE
Origin summaries do not always match their actual powers

### ISSUE THREAD

**Issue by A5ho9999** [muon-rw/Medieval-Origins-Old#78]
Can't seem to set fall_immunity on alfiq. When selecting the origin in-game it still takes fall damage. Also it will still display carnivore in the description even if it's toggled off.

MC: 1.20.1
Version: 6.3.3+1.20.1 Fabric
Loader: 15.11

```
"medievalorigins:alfiq": {
      "enabled": true,
      "origins:fall_immunity": true,
      "origins:sprint_jump": true,
      "origins:velvet_paws": true,
      "origins:scare_creepers": true,
      "medievalorigins:alfiq/clawed": false,
      "medievalorigins:alfiq/poor_grip": true,
      "medievalorigins:alfiq/agile_preference": false,
      "medievalorigins:alfiq/crepuscular": true,
      "medievalorigins:alfiq/pickpocket": false,
      "medievalorigins:alfiq/pickpocket_player": false,
      "medievalorigins:alfiq/pounce": true,
      "medievalorigins:alfiq/meow": true,
      "medievalorigins:alfiq/on_your_feet": false,
      "origins:carnivore": false
    },
```

**Comment by muon-rw** [comment]
Hi, you can’t add new powers (fall_immunity) using the Origins config like that, it’s only for disabling. To add a power, you’ll need to make a datapack that replaces the Alfiq origin with a higher loading priority (or you could instead replace `on_your_feet` to work on any damage amount, which I’d recommend). You can ask on the Origins discord if you need help with it.

The carnivore issue is odd. Can you send your `latest.log` from the logs folder after disabling the power, restarting the game, and reselecting Alfiq?

**Comment by A5ho9999** [comment]
Oh I see, thank you.

As for the carnivore issue, I mean the fact it's hard coded into the [language](https://github.com/muon-rw/Medieval-Origins-Revival/blob/c72453bf78fbebe9658e3020bd1e91d677f51856/src/main/resources/assets/medievalorigins/lang/en_us.json#L5) file. So I'll just have to override it with a resource pack is all. Thanks for the response.

**Comment by muon-rw** [comment]
I see. Yeah, the summaries being manual isn’t ideal but it would require some pretty robust overengineering and is pretty low priority since, like you say, it can just be changed with a resource pack in the rare case people make changes to the origins.
