### ISSUE TITLE
Origins - Siren performance issue

### ISSUE THREAD

**Issue by SojaIntegral** [muon-rw/Medieval-Origins-Old#81]
The Siren origin is severely impacting MSPT, causing the game to freeze every once in a while when entities are hurt (by player, environment or anything else).

[Spark log](https://spark.lucko.me/WjlAWaYuvD)

**Comment by muon-rw** [comment]
Duplicate of https://github.com/muon-rw/Medieval-Origins-Revival/issues/69 

It's a simple fix, but the Forge version just hasn't been updated in awhile

For now, you can disable Siren Song in the `origins-common` config
