### ISSUE TITLE
Ogre and Goblin infinite wall jump.

### ISSUE THREAD

**Issue by Zarkanar** [muon-rw/Medieval-Origins-Old#83]
Found out if you have Valkyrienskies installed both the Ogre and the Goblin have a bug where they can jump up a wall endlessly gaining momentum as long as there's still a straight wall in front of them.

I do have Pehkui installed as well but it only happens when I have Valkyrienskies enabled, taking Valk out removes the issue.

valkyrienskies-120-2.3.0-beta.5
medievalorigins-6.2.5+1.20.1-forge
Versions of the mods I'm using.

**Comment by muon-rw** [comment]
I really don't have the time to diagnose issues with a mod as invasive as Valkyrien Skies, sorry. 

It's more accurately a Pehkui issue anyway, since all those origins do is use their scale data types. You could try reporting it to them.
