### ISSUE TITLE
(question) Regaring Featherweight

### ISSUE THREAD

**Issue by ItzLucaGER** [muon-rw/Medieval-Origins-Old#92]
Not a bug, just a question that I dont know where else to ask. Im currently trying to get the entchantment featherweight. The only info I could find was in the changelog when it was added. It says it can be found in dungeons or gotten at a lvl 45 enchanting table. That confused me a little. Isn't level 30 (15 bookshelf) the max amount? Also can it be traded from villagers maybe?

**Comment by muon-rw** [comment]
It can also be traded from villagers, yeah. 

Where are you seeing that it's only obtainable at level 45? It's a treasure enchantment, which means by default it can't be obtained from the enchanting table at all.

**Comment by ItzLucaGER** [comment]
Oh I think that was a different medieval origins mod. My bad D: Anyways thanks for the help, so glad it can be traded xD
