### ISSUE TITLE
High Elf Instant Cure

### ISSUE THREAD

**Issue by yanalvesrj** [muon-rw/Medieval-Origins-Old#98]
High Elf Instant Cure is not working at the 1.20.1 a click with right buttom on Zombie NPC Villager with a Golden Apple and happens nothing.

**Comment by muon-rw** [comment]
Can you send a log with you attempting to use the power?

**Comment by yanalvesrj** [comment]
Sure! i'll send an video too. 
![log-origins](https://github.com/muon-rw/Medieval-Origins-Revival/assets/69536502/bdde105c-5000-415c-bcaf-4b84e5563b14)

**Comment by yanalvesrj** [comment]
https://github.com/muon-rw/Medieval-Origins-Revival/assets/69536502/180731c5-03c6-45a6-b636-0849e8379626

**Comment by yanalvesrj** [comment]
https://github.com/muon-rw/Medieval-Origins-Revival/assets/69536502/33cbee3c-5c66-47cd-a362-928fac7b754c

**Comment by z-haopeng** [comment]
Looking through the code, it seems like the High Elf origin just doesn't have the Instant Cure power listed. I made a dead simple PR (#103) that I think should fix it (tested by applying the change with a datapack).

**Comment by muon-rw** [comment]
Oh yeah, *I removed it* intentionally… I just forgot to remove the badge. Something else is planned!

**Comment by yanalvesrj** [comment]
> Looking through the code, it seems like the High Elf origin just doesn't have the Instant Cure power listed. I made a dead simple PR (#103) that I think should fix it (tested by applying the change with a datapack).

I see! Thanks all! Now is just i create a origins.json in my datapack folder and paste that line to there?

**Comment by muon-rw** [comment]
If you want to use this with High Elf you can override `/data/medievalorigins/origins/high_elf.json` with a datapack - You'll also need to set a higher loading priority

**Comment by yanalvesrj** [comment]
> If you want to use this with High Elf you can override `/data/medievalorigins/origins/high_elf.json` with a datapack - You'll also need to set a higher loading priority

I don't know how to do that LOL, i can't find my /data/medievalorigins/origins/high_elf.json 

but i appreciate all help! Thanks a lot :)
